version: '3'

tasks: 
  build:
    dir: cmd/shortener
    cmds: 
      - go build -o shortener.exe
  
  start:
    dir: cmd/shortener
    cmds:
      - task: build
      - shortener.exe {{.CLI_ARGS}}

  vet:
    cmds:
      - go vet -vettool=statictest ./...
  
  autotest:
    cmds:
      - task: build
      - shortenertest -test.v -test.run=^TestIteration{{.ITER}}$ -binary-path=cmd/shortener/shortener -source-path=. {{.CLI_ARGS}}
